<?php

namespace Proxies\__CG__\OroCRM\Bundle\MagentoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MagentoSoapTransport extends \OroCRM\Bundle\MagentoBundle\Entity\MagentoSoapTransport implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'wsdlUrl', 'apiUser', 'apiKey', 'syncStartDate', 'initialSyncStartDate', 'syncRange', 'websiteId', 'websites', 'isExtensionInstalled', 'extensionVersion', 'magentoVersion', 'isWsiMode', 'guestCustomerSync', 'adminUrl', 'wsdlCachePath', 'settings', 'id');
        }

        return array('__isInitialized__', 'wsdlUrl', 'apiUser', 'apiKey', 'syncStartDate', 'initialSyncStartDate', 'syncRange', 'websiteId', 'websites', 'isExtensionInstalled', 'extensionVersion', 'magentoVersion', 'isWsiMode', 'guestCustomerSync', 'adminUrl', 'wsdlCachePath', 'settings', 'id');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MagentoSoapTransport $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setWsdlUrl($wsdlUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWsdlUrl', array($wsdlUrl));

        return parent::setWsdlUrl($wsdlUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getWsdlUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWsdlUrl', array());

        return parent::getWsdlUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setApiUser($apiUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApiUser', array($apiUser));

        return parent::setApiUser($apiUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getApiUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApiUser', array());

        return parent::getApiUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setApiKey($apiKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApiKey', array($apiKey));

        return parent::setApiKey($apiKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getApiKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApiKey', array());

        return parent::getApiKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setSyncStartDate(\DateTime $syncStartDate = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSyncStartDate', array($syncStartDate));

        return parent::setSyncStartDate($syncStartDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getSyncStartDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSyncStartDate', array());

        return parent::getSyncStartDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setSyncRange($syncRange)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSyncRange', array($syncRange));

        return parent::setSyncRange($syncRange);
    }

    /**
     * {@inheritDoc}
     */
    public function getSyncRange()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSyncRange', array());

        return parent::getSyncRange();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsiteId($websiteId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsiteId', array($websiteId));

        return parent::setWebsiteId($websiteId);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsiteId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsiteId', array());

        return parent::getWebsiteId();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsites(array $websites)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsites', array($websites));

        return parent::setWebsites($websites);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsites()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsites', array());

        return parent::getWebsites();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsExtensionInstalled($isExtensionInstalled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsExtensionInstalled', array($isExtensionInstalled));

        return parent::setIsExtensionInstalled($isExtensionInstalled);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsExtensionInstalled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsExtensionInstalled', array());

        return parent::getIsExtensionInstalled();
    }

    /**
     * {@inheritDoc}
     */
    public function getExtensionVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtensionVersion', array());

        return parent::getExtensionVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtensionVersion($extensionVersion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtensionVersion', array($extensionVersion));

        return parent::setExtensionVersion($extensionVersion);
    }

    /**
     * {@inheritDoc}
     */
    public function isSupportedExtensionVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSupportedExtensionVersion', array());

        return parent::isSupportedExtensionVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function getMagentoVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMagentoVersion', array());

        return parent::getMagentoVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setMagentoVersion($magentoVersion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMagentoVersion', array($magentoVersion));

        return parent::setMagentoVersion($magentoVersion);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsWsiMode($isWsiMode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsWsiMode', array($isWsiMode));

        return parent::setIsWsiMode($isWsiMode);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsWsiMode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsWsiMode', array());

        return parent::getIsWsiMode();
    }

    /**
     * {@inheritDoc}
     */
    public function setGuestCustomerSync($guestCustomerSync)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGuestCustomerSync', array($guestCustomerSync));

        return parent::setGuestCustomerSync($guestCustomerSync);
    }

    /**
     * {@inheritDoc}
     */
    public function getGuestCustomerSync()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuestCustomerSync', array());

        return parent::getGuestCustomerSync();
    }

    /**
     * {@inheritDoc}
     */
    public function getSettingsBag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSettingsBag', array());

        return parent::getSettingsBag();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdminUrl($adminUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdminUrl', array($adminUrl));

        return parent::setAdminUrl($adminUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdminUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminUrl', array());

        return parent::getAdminUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function getInitialSyncStartDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInitialSyncStartDate', array());

        return parent::getInitialSyncStartDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setInitialSyncStartDate($initialSyncStartDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInitialSyncStartDate', array($initialSyncStartDate));

        return parent::setInitialSyncStartDate($initialSyncStartDate);
    }

    /**
     * {@inheritDoc}
     */
    public function setWsdlCachePath($wsdlCachePath)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWsdlCachePath', array($wsdlCachePath));

        return parent::setWsdlCachePath($wsdlCachePath);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

}
