<?php

namespace Proxies\__CG__\Oro\Bundle\WorkflowBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WorkflowDefinition extends \Oro\Bundle\WorkflowBundle\Entity\WorkflowDefinition implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'name', 'label', 'relatedEntity', 'entityAttributeName', 'stepsDisplayOrdered', 'system', 'configuration', 'steps', 'startStep', 'entityAcls', 'createdAt', 'updatedAt');
        }

        return array('__isInitialized__', 'name', 'label', 'relatedEntity', 'entityAttributeName', 'stepsDisplayOrdered', 'system', 'configuration', 'steps', 'startStep', 'entityAcls', 'createdAt', 'updatedAt');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (WorkflowDefinition $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getName();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabel($label)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabel', array($label));

        return parent::setLabel($label);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', array());

        return parent::getLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedEntity($relatedEntity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedEntity', array($relatedEntity));

        return parent::setRelatedEntity($relatedEntity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedEntity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedEntity', array());

        return parent::getRelatedEntity();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntityAttributeName($entityAttributeName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntityAttributeName', array($entityAttributeName));

        return parent::setEntityAttributeName($entityAttributeName);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityAttributeName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityAttributeName', array());

        return parent::getEntityAttributeName();
    }

    /**
     * {@inheritDoc}
     */
    public function isStepsDisplayOrdered()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isStepsDisplayOrdered', array());

        return parent::isStepsDisplayOrdered();
    }

    /**
     * {@inheritDoc}
     */
    public function setStepsDisplayOrdered($stepsDisplayOrdered)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStepsDisplayOrdered', array($stepsDisplayOrdered));

        return parent::setStepsDisplayOrdered($stepsDisplayOrdered);
    }

    /**
     * {@inheritDoc}
     */
    public function setConfiguration($configuration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfiguration', array($configuration));

        return parent::setConfiguration($configuration);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfiguration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfiguration', array());

        return parent::getConfiguration();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartStep($startStep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartStep', array($startStep));

        return parent::setStartStep($startStep);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartStep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartStep', array());

        return parent::getStartStep();
    }

    /**
     * {@inheritDoc}
     */
    public function getSteps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSteps', array());

        return parent::getSteps();
    }

    /**
     * {@inheritDoc}
     */
    public function setSteps($steps)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSteps', array($steps));

        return parent::setSteps($steps);
    }

    /**
     * {@inheritDoc}
     */
    public function addStep(\Oro\Bundle\WorkflowBundle\Entity\WorkflowStep $step)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addStep', array($step));

        return parent::addStep($step);
    }

    /**
     * {@inheritDoc}
     */
    public function removeStep(\Oro\Bundle\WorkflowBundle\Entity\WorkflowStep $step)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeStep', array($step));

        return parent::removeStep($step);
    }

    /**
     * {@inheritDoc}
     */
    public function hasStepByName($stepName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasStepByName', array($stepName));

        return parent::hasStepByName($stepName);
    }

    /**
     * {@inheritDoc}
     */
    public function getStepByName($stepName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStepByName', array($stepName));

        return parent::getStepByName($stepName);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityAcls()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityAcls', array());

        return parent::getEntityAcls();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntityAcls($entityAcl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntityAcls', array($entityAcl));

        return parent::setEntityAcls($entityAcl);
    }

    /**
     * {@inheritDoc}
     */
    public function addEntityAcl(\Oro\Bundle\WorkflowBundle\Entity\WorkflowEntityAcl $acl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEntityAcl', array($acl));

        return parent::addEntityAcl($acl);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEntityAcl(\Oro\Bundle\WorkflowBundle\Entity\WorkflowEntityAcl $acl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEntityAcl', array($acl));

        return parent::removeEntityAcl($acl);
    }

    /**
     * {@inheritDoc}
     */
    public function hasEntityAclByAttributeStep($attributeStep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasEntityAclByAttributeStep', array($attributeStep));

        return parent::hasEntityAclByAttributeStep($attributeStep);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityAclByAttributeStep($attributeStep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityAclByAttributeStep', array($attributeStep));

        return parent::getEntityAclByAttributeStep($attributeStep);
    }

    /**
     * {@inheritDoc}
     */
    public function import(\Oro\Bundle\WorkflowBundle\Entity\WorkflowDefinition $definition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'import', array($definition));

        return parent::import($definition);
    }

    /**
     * {@inheritDoc}
     */
    public function isSystem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSystem', array());

        return parent::isSystem();
    }

    /**
     * {@inheritDoc}
     */
    public function setSystem($system)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSystem', array($system));

        return parent::setSystem($system);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($created));

        return parent::setCreatedAt($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updated));

        return parent::setUpdatedAt($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function beforeSave()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'beforeSave', array());

        return parent::beforeSave();
    }

    /**
     * {@inheritDoc}
     */
    public function beforeUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'beforeUpdate', array());

        return parent::beforeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getObjectIdentifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjectIdentifier', array());

        return parent::getObjectIdentifier();
    }

}
