<?php

namespace Proxies\__CG__\OroCRM\Bundle\MagentoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Order extends \OroCRM\Bundle\MagentoBundle\Entity\Order implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'incrementId', 'customer', 'addresses', 'store', 'isVirtual', 'isGuest', 'giftMessage', 'remoteIp', 'storeName', 'totalPaidAmount', 'totalInvoicedAmount', 'totalRefundedAmount', 'totalCanceledAmount', 'cart', 'items', 'relatedCalls', 'relatedEmails', 'notes', 'feedback', 'workflowItem', 'workflowStep', 'customerEmail', 'owner', 'organization', 'id', 'currency', 'paymentMethod', 'paymentDetails', 'subtotalAmount', 'shippingAmount', 'shippingMethod', 'taxAmount', 'discountAmount', 'discountPercent', 'totalAmount', 'status', 'createdAt', 'updatedAt', 'channel', 'firstName', 'lastName', 'dataChannel');
        }

        return array('__isInitialized__', 'incrementId', 'customer', 'addresses', 'store', 'isVirtual', 'isGuest', 'giftMessage', 'remoteIp', 'storeName', 'totalPaidAmount', 'totalInvoicedAmount', 'totalRefundedAmount', 'totalCanceledAmount', 'cart', 'items', 'relatedCalls', 'relatedEmails', 'notes', 'feedback', 'workflowItem', 'workflowStep', 'customerEmail', 'owner', 'organization', 'id', 'currency', 'paymentMethod', 'paymentDetails', 'subtotalAmount', 'shippingAmount', 'shippingMethod', 'taxAmount', 'discountAmount', 'discountPercent', 'totalAmount', 'status', 'createdAt', 'updatedAt', 'channel', 'firstName', 'lastName', 'dataChannel');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Order $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setWorkflowItem($workflowItem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkflowItem', array($workflowItem));

        return parent::setWorkflowItem($workflowItem);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkflowItem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkflowItem', array());

        return parent::getWorkflowItem();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorkflowStep($workflowStep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkflowStep', array($workflowStep));

        return parent::setWorkflowStep($workflowStep);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkflowStep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkflowStep', array());

        return parent::getWorkflowStep();
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedCalls()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedCalls', array());

        return parent::getRelatedCalls();
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedCall(\OroCRM\Bundle\CallBundle\Entity\Call $call)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedCall', array($call));

        return parent::addRelatedCall($call);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedCall(\OroCRM\Bundle\CallBundle\Entity\Call $call)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedCall', array($call));

        return parent::removeRelatedCall($call);
    }

    /**
     * {@inheritDoc}
     */
    public function hasRelatedCall(\OroCRM\Bundle\CallBundle\Entity\Call $call)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasRelatedCall', array($call));

        return parent::hasRelatedCall($call);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedEmails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedEmails', array());

        return parent::getRelatedEmails();
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedEmail(\Oro\Bundle\EmailBundle\Entity\Email $email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedEmail', array($email));

        return parent::addRelatedEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedEmail(\Oro\Bundle\EmailBundle\Entity\Email $email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedEmail', array($email));

        return parent::removeRelatedEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function hasRelatedEmail(\Oro\Bundle\EmailBundle\Entity\Email $email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasRelatedEmail', array($email));

        return parent::hasRelatedEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setIncrementId($incrementId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIncrementId', array($incrementId));

        return parent::setIncrementId($incrementId);
    }

    /**
     * {@inheritDoc}
     */
    public function getIncrementId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIncrementId', array());

        return parent::getIncrementId();
    }

    /**
     * {@inheritDoc}
     */
    public function setGiftMessage($giftMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGiftMessage', array($giftMessage));

        return parent::setGiftMessage($giftMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getGiftMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGiftMessage', array());

        return parent::getGiftMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsGuest($isGuest)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsGuest', array($isGuest));

        return parent::setIsGuest($isGuest);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsGuest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsGuest', array());

        return parent::getIsGuest();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsVirtual($isVirtual)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsVirtual', array($isVirtual));

        return parent::setIsVirtual($isVirtual);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsVirtual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsVirtual', array());

        return parent::getIsVirtual();
    }

    /**
     * {@inheritDoc}
     */
    public function setStore(\OroCRM\Bundle\MagentoBundle\Entity\Store $store)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStore', array($store));

        return parent::setStore($store);
    }

    /**
     * {@inheritDoc}
     */
    public function getStore()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStore', array());

        return parent::getStore();
    }

    /**
     * {@inheritDoc}
     */
    public function setStoreName($storeName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStoreName', array($storeName));

        return parent::setStoreName($storeName);
    }

    /**
     * {@inheritDoc}
     */
    public function getStoreName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStoreName', array());

        return parent::getStoreName();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalCanceledAmount($totalCanceledAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalCanceledAmount', array($totalCanceledAmount));

        return parent::setTotalCanceledAmount($totalCanceledAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalCanceledAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalCanceledAmount', array());

        return parent::getTotalCanceledAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalInvoicedAmount($totalInvoicedAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalInvoicedAmount', array($totalInvoicedAmount));

        return parent::setTotalInvoicedAmount($totalInvoicedAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalInvoicedAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalInvoicedAmount', array());

        return parent::getTotalInvoicedAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalPaidAmount($totalPaidAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalPaidAmount', array($totalPaidAmount));

        return parent::setTotalPaidAmount($totalPaidAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalPaidAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalPaidAmount', array());

        return parent::getTotalPaidAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalRefundedAmount($totalRefundedAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalRefundedAmount', array($totalRefundedAmount));

        return parent::setTotalRefundedAmount($totalRefundedAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalRefundedAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalRefundedAmount', array());

        return parent::getTotalRefundedAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemoteIp($remoteIp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemoteIp', array($remoteIp));

        return parent::setRemoteIp($remoteIp);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemoteIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemoteIp', array());

        return parent::getRemoteIp();
    }

    /**
     * {@inheritDoc}
     */
    public function setCart($cart = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCart', array($cart));

        return parent::setCart($cart);
    }

    /**
     * {@inheritDoc}
     */
    public function getCart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCart', array());

        return parent::getCart();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotes($notes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotes', array($notes));

        return parent::setNotes($notes);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotes', array());

        return parent::getNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeedback($feedback)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeedback', array($feedback));

        return parent::setFeedback($feedback);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeedback()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeedback', array());

        return parent::getFeedback();
    }

    /**
     * {@inheritDoc}
     */
    public function beforeSave()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'beforeSave', array());

        return parent::beforeSave();
    }

    /**
     * {@inheritDoc}
     */
    public function doPreUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'doPreUpdate', array());

        return parent::doPreUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingAddress', array());

        return parent::getBillingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerEmail($customerEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerEmail', array($customerEmail));

        return parent::setCustomerEmail($customerEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerEmail', array());

        return parent::getCustomerEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwner', array());

        return parent::getOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwner(\Oro\Bundle\UserBundle\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwner', array($user));

        return parent::setOwner($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganization(\Oro\Bundle\OrganizationBundle\Entity\Organization $organization = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganization', array($organization));

        return parent::setOrganization($organization);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganization()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganization', array());

        return parent::getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomer($customer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomer', array($customer));

        return parent::setCustomer($customer);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer', array());

        return parent::getCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function resetAddresses($addresses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'resetAddresses', array($addresses));

        return parent::resetAddresses($addresses);
    }

    /**
     * {@inheritDoc}
     */
    public function addAddress(\Oro\Bundle\AddressBundle\Entity\AbstractAddress $address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAddress', array($address));

        return parent::addAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAddress(\Oro\Bundle\AddressBundle\Entity\AbstractAddress $address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAddress', array($address));

        return parent::removeAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddresses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddresses', array());

        return parent::getAddresses();
    }

    /**
     * {@inheritDoc}
     */
    public function hasAddress(\Oro\Bundle\AddressBundle\Entity\AbstractAddress $address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasAddress', array($address));

        return parent::hasAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentDetails($paymentDetails)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentDetails', array($paymentDetails));

        return parent::setPaymentDetails($paymentDetails);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentDetails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentDetails', array());

        return parent::getPaymentDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentMethod($paymentMethod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentMethod', array($paymentMethod));

        return parent::setPaymentMethod($paymentMethod);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentMethod', array());

        return parent::getPaymentMethod();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscountAmount($discountAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscountAmount', array($discountAmount));

        return parent::setDiscountAmount($discountAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountAmount', array());

        return parent::getDiscountAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscountPercent($discountPercent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscountPercent', array($discountPercent));

        return parent::setDiscountPercent($discountPercent);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountPercent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountPercent', array());

        return parent::getDiscountPercent();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingAmount($shippingAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingAmount', array($shippingAmount));

        return parent::setShippingAmount($shippingAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency($currency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', array($currency));

        return parent::setCurrency($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', array());

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingMethod($shippingMethod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingMethod', array($shippingMethod));

        return parent::setShippingMethod($shippingMethod);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingMethod', array());

        return parent::getShippingMethod();
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingAmount', array());

        return parent::getShippingAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubtotalAmount($subtotalAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubtotalAmount', array($subtotalAmount));

        return parent::setSubtotalAmount($subtotalAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubtotalAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubtotalAmount', array());

        return parent::getSubtotalAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxAmount($taxAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxAmount', array($taxAmount));

        return parent::setTaxAmount($taxAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxAmount', array());

        return parent::getTaxAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalAmount($totalAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalAmount', array($totalAmount));

        return parent::setTotalAmount($totalAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalAmount', array());

        return parent::getTotalAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setItems($items)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItems', array($items));

        return parent::setItems($items);
    }

    /**
     * {@inheritDoc}
     */
    public function getItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItems', array());

        return parent::getItems();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataChannel(\OroCRM\Bundle\ChannelBundle\Entity\Channel $channel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataChannel', array($channel));

        return parent::setDataChannel($channel);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataChannel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataChannel', array());

        return parent::getDataChannel();
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', array());

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', array());

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setChannel(\Oro\Bundle\IntegrationBundle\Entity\Channel $integration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChannel', array($integration));

        return parent::setChannel($integration);
    }

    /**
     * {@inheritDoc}
     */
    public function getChannel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChannel', array());

        return parent::getChannel();
    }

    /**
     * {@inheritDoc}
     */
    public function getChannelName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChannelName', array());

        return parent::getChannelName();
    }

}
