<?php

namespace Proxies\__CG__\Oro\Bundle\ActivityListBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ActivityList extends \Oro\Bundle\ActivityListBundle\Entity\ActivityList implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'owner', 'editor', 'verb', 'subject', 'description', 'head', 'relatedActivityClass', 'relatedActivityId', 'createdAt', 'updatedAt', 'organization', 'activityOwners', 'user_10c9f691', 'opportunity_c8bd867a', 'lead_272269fb', 'customer_8fc2c3ea', 'contact_e8d5b2ba', 'case_entity_a4fb53f5', 'b2b_customer_2bf513a9', 'account_2d83b3af');
        }

        return array('__isInitialized__', 'id', 'owner', 'editor', 'verb', 'subject', 'description', 'head', 'relatedActivityClass', 'relatedActivityId', 'createdAt', 'updatedAt', 'organization', 'activityOwners', 'user_10c9f691', 'opportunity_c8bd867a', 'lead_272269fb', 'customer_8fc2c3ea', 'contact_e8d5b2ba', 'case_entity_a4fb53f5', 'b2b_customer_2bf513a9', 'account_2d83b3af');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ActivityList $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function addActivityOwner(\Oro\Bundle\ActivityListBundle\Entity\ActivityOwner $activityOwner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addActivityOwner', array($activityOwner));

        return parent::addActivityOwner($activityOwner);
    }

    /**
     * {@inheritDoc}
     */
    public function removeActivityOwner(\Oro\Bundle\ActivityListBundle\Entity\ActivityOwner $activityOwner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeActivityOwner', array($activityOwner));

        return parent::removeActivityOwner($activityOwner);
    }

    /**
     * {@inheritDoc}
     */
    public function hasActivityOwner(\Oro\Bundle\ActivityListBundle\Entity\ActivityOwner $activityOwner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasActivityOwner', array($activityOwner));

        return parent::hasActivityOwner($activityOwner);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivityOwners()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivityOwners', array());

        return parent::getActivityOwners();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getVerb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVerb', array());

        return parent::getVerb();
    }

    /**
     * {@inheritDoc}
     */
    public function setVerb($verb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVerb', array($verb));

        return parent::setVerb($verb);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubject', array());

        return parent::getSubject();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubject($subject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubject', array($subject));

        return parent::setSubject($subject);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function isHead()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isHead', array());

        return parent::isHead();
    }

    /**
     * {@inheritDoc}
     */
    public function setHead($head)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHead', array($head));

        return parent::setHead($head);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganization()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganization', array());

        return parent::getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganization(\Oro\Bundle\OrganizationBundle\Entity\Organization $organization = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganization', array($organization));

        return parent::setOrganization($organization);
    }

    /**
     * {@inheritDoc}
     */
    public function setOwner(\Oro\Bundle\UserBundle\Entity\User $owningUser = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwner', array($owningUser));

        return parent::setOwner($owningUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwner', array());

        return parent::getOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedActivityClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedActivityClass', array());

        return parent::getRelatedActivityClass();
    }

    /**
     * {@inheritDoc}
     */
    public function setEditor(\Oro\Bundle\UserBundle\Entity\User $editor = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEditor', array($editor));

        return parent::setEditor($editor);
    }

    /**
     * {@inheritDoc}
     */
    public function getEditor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEditor', array());

        return parent::getEditor();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedActivityClass($relatedActivityClass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedActivityClass', array($relatedActivityClass));

        return parent::setRelatedActivityClass($relatedActivityClass);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedActivityId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedActivityId', array());

        return parent::getRelatedActivityId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedActivityId($relatedActivityId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedActivityId', array($relatedActivityId));

        return parent::setRelatedActivityId($relatedActivityId);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function supportActivityListTarget($targetClass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'supportActivityListTarget', array($targetClass));

        return parent::supportActivityListTarget($targetClass);
    }

    /**
     * {@inheritDoc}
     */
    public function setUser10c9f691($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser10c9f691', array($value));

        return parent::setUser10c9f691($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setOpportunityC8bd867a($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpportunityC8bd867a', array($value));

        return parent::setOpportunityC8bd867a($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setLead272269fb($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLead272269fb', array($value));

        return parent::setLead272269fb($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomer8fc2c3ea($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomer8fc2c3ea', array($value));

        return parent::setCustomer8fc2c3ea($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setContactE8d5b2ba($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactE8d5b2ba', array($value));

        return parent::setContactE8d5b2ba($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setCaseEntityA4fb53f5($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaseEntityA4fb53f5', array($value));

        return parent::setCaseEntityA4fb53f5($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setB2bCustomer2bf513a9($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setB2bCustomer2bf513a9', array($value));

        return parent::setB2bCustomer2bf513a9($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setAccount2d83b3af($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccount2d83b3af', array($value));

        return parent::setAccount2d83b3af($value);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUser10c9f691($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUser10c9f691', array($value));

        return parent::removeUser10c9f691($value);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOpportunityC8bd867a($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOpportunityC8bd867a', array($value));

        return parent::removeOpportunityC8bd867a($value);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLead272269fb($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLead272269fb', array($value));

        return parent::removeLead272269fb($value);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCustomer8fc2c3ea($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCustomer8fc2c3ea', array($value));

        return parent::removeCustomer8fc2c3ea($value);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContactE8d5b2ba($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContactE8d5b2ba', array($value));

        return parent::removeContactE8d5b2ba($value);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCaseEntityA4fb53f5($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCaseEntityA4fb53f5', array($value));

        return parent::removeCaseEntityA4fb53f5($value);
    }

    /**
     * {@inheritDoc}
     */
    public function removeB2bCustomer2bf513a9($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeB2bCustomer2bf513a9', array($value));

        return parent::removeB2bCustomer2bf513a9($value);
    }

    /**
     * {@inheritDoc}
     */
    public function removeActivityListTarget($target)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeActivityListTarget', array($target));

        return parent::removeActivityListTarget($target);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAccount2d83b3af($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAccount2d83b3af', array($value));

        return parent::removeAccount2d83b3af($value);
    }

    /**
     * {@inheritDoc}
     */
    public function hasActivityListTarget($target)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasActivityListTarget', array($target));

        return parent::hasActivityListTarget($target);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser10c9f691()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser10c9f691', array());

        return parent::getUser10c9f691();
    }

    /**
     * {@inheritDoc}
     */
    public function getOpportunityC8bd867a()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpportunityC8bd867a', array());

        return parent::getOpportunityC8bd867a();
    }

    /**
     * {@inheritDoc}
     */
    public function getLead272269fb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLead272269fb', array());

        return parent::getLead272269fb();
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer8fc2c3ea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer8fc2c3ea', array());

        return parent::getCustomer8fc2c3ea();
    }

    /**
     * {@inheritDoc}
     */
    public function getContactE8d5b2ba()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactE8d5b2ba', array());

        return parent::getContactE8d5b2ba();
    }

    /**
     * {@inheritDoc}
     */
    public function getCaseEntityA4fb53f5()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaseEntityA4fb53f5', array());

        return parent::getCaseEntityA4fb53f5();
    }

    /**
     * {@inheritDoc}
     */
    public function getB2bCustomer2bf513a9()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getB2bCustomer2bf513a9', array());

        return parent::getB2bCustomer2bf513a9();
    }

    /**
     * {@inheritDoc}
     */
    public function getActivityListTargets($targetClass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivityListTargets', array($targetClass));

        return parent::getActivityListTargets($targetClass);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivityListTargetEntities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivityListTargetEntities', array());

        return parent::getActivityListTargetEntities();
    }

    /**
     * {@inheritDoc}
     */
    public function getAccount2d83b3af()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccount2d83b3af', array());

        return parent::getAccount2d83b3af();
    }

    /**
     * {@inheritDoc}
     */
    public function addUser10c9f691($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUser10c9f691', array($value));

        return parent::addUser10c9f691($value);
    }

    /**
     * {@inheritDoc}
     */
    public function addOpportunityC8bd867a($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOpportunityC8bd867a', array($value));

        return parent::addOpportunityC8bd867a($value);
    }

    /**
     * {@inheritDoc}
     */
    public function addLead272269fb($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLead272269fb', array($value));

        return parent::addLead272269fb($value);
    }

    /**
     * {@inheritDoc}
     */
    public function addCustomer8fc2c3ea($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCustomer8fc2c3ea', array($value));

        return parent::addCustomer8fc2c3ea($value);
    }

    /**
     * {@inheritDoc}
     */
    public function addContactE8d5b2ba($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContactE8d5b2ba', array($value));

        return parent::addContactE8d5b2ba($value);
    }

    /**
     * {@inheritDoc}
     */
    public function addCaseEntityA4fb53f5($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCaseEntityA4fb53f5', array($value));

        return parent::addCaseEntityA4fb53f5($value);
    }

    /**
     * {@inheritDoc}
     */
    public function addB2bCustomer2bf513a9($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addB2bCustomer2bf513a9', array($value));

        return parent::addB2bCustomer2bf513a9($value);
    }

    /**
     * {@inheritDoc}
     */
    public function addActivityListTarget($target)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addActivityListTarget', array($target));

        return parent::addActivityListTarget($target);
    }

    /**
     * {@inheritDoc}
     */
    public function addAccount2d83b3af($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAccount2d83b3af', array($value));

        return parent::addAccount2d83b3af($value);
    }

}
