<?php

namespace Proxies\__CG__\Oro\Bundle\EmailBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Email extends \Oro\Bundle\EmailBundle\Entity\Email implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'created', 'subject', 'fromName', 'fromEmailAddress', 'recipients', 'sentAt', 'importance', 'internalDate', 'head', 'messageId', 'multiMessageId', 'xMessageId', 'thread', 'xThreadId', 'refs', 'emailBody', 'emailUsers', 'acceptLanguageHeader', 'user_d41b1c4b', 'opportunity_c1908b8f', 'lead_e5b9c444', 'customer_14831de6', 'contact_cdc90e7a', 'case_entity_81e7ef35', 'b2b_customer_22d81e5c', 'account_89f0f6f');
        }

        return array('__isInitialized__', 'id', 'created', 'subject', 'fromName', 'fromEmailAddress', 'recipients', 'sentAt', 'importance', 'internalDate', 'head', 'messageId', 'multiMessageId', 'xMessageId', 'thread', 'xThreadId', 'refs', 'emailBody', 'emailUsers', 'acceptLanguageHeader', 'user_d41b1c4b', 'opportunity_c1908b8f', 'lead_e5b9c444', 'customer_14831de6', 'contact_cdc90e7a', 'case_entity_81e7ef35', 'b2b_customer_22d81e5c', 'account_89f0f6f');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Email $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', array($created));

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubject', array());

        return parent::getSubject();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubject($subject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubject', array($subject));

        return parent::setSubject($subject);
    }

    /**
     * {@inheritDoc}
     */
    public function getFromName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFromName', array());

        return parent::getFromName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFromName($fromName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFromName', array($fromName));

        return parent::setFromName($fromName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFromEmailAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFromEmailAddress', array());

        return parent::getFromEmailAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setFromEmailAddress(\Oro\Bundle\EmailBundle\Entity\EmailAddress $fromEmailAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFromEmailAddress', array($fromEmailAddress));

        return parent::setFromEmailAddress($fromEmailAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecipients($recipientType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecipients', array($recipientType));

        return parent::getRecipients($recipientType);
    }

    /**
     * {@inheritDoc}
     */
    public function addRecipient(\Oro\Bundle\EmailBundle\Entity\EmailRecipient $recipient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRecipient', array($recipient));

        return parent::addRecipient($recipient);
    }

    /**
     * {@inheritDoc}
     */
    public function getSentAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSentAt', array());

        return parent::getSentAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setSentAt($sentAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSentAt', array($sentAt));

        return parent::setSentAt($sentAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getImportance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImportance', array());

        return parent::getImportance();
    }

    /**
     * {@inheritDoc}
     */
    public function setImportance($importance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImportance', array($importance));

        return parent::setImportance($importance);
    }

    /**
     * {@inheritDoc}
     */
    public function getInternalDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInternalDate', array());

        return parent::getInternalDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setInternalDate($internalDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInternalDate', array($internalDate));

        return parent::setInternalDate($internalDate);
    }

    /**
     * {@inheritDoc}
     */
    public function isHead()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isHead', array());

        return parent::isHead();
    }

    /**
     * {@inheritDoc}
     */
    public function setHead($head)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHead', array($head));

        return parent::setHead($head);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessageId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessageId', array());

        return parent::getMessageId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessageId($messageId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessageId', array($messageId));

        return parent::setMessageId($messageId);
    }

    /**
     * {@inheritDoc}
     */
    public function getMultiMessageId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMultiMessageId', array());

        return parent::getMultiMessageId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMultiMessageId($multiMessageId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMultiMessageId', array($multiMessageId));

        return parent::setMultiMessageId($multiMessageId);
    }

    /**
     * {@inheritDoc}
     */
    public function getXMessageId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getXMessageId', array());

        return parent::getXMessageId();
    }

    /**
     * {@inheritDoc}
     */
    public function setXMessageId($xMessageId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setXMessageId', array($xMessageId));

        return parent::setXMessageId($xMessageId);
    }

    /**
     * {@inheritDoc}
     */
    public function getXThreadId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getXThreadId', array());

        return parent::getXThreadId();
    }

    /**
     * {@inheritDoc}
     */
    public function setXThreadId($xThreadId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setXThreadId', array($xThreadId));

        return parent::setXThreadId($xThreadId);
    }

    /**
     * {@inheritDoc}
     */
    public function getThread()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThread', array());

        return parent::getThread();
    }

    /**
     * {@inheritDoc}
     */
    public function setThread($thread)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThread', array($thread));

        return parent::setThread($thread);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefs', array());

        return parent::getRefs();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefs($refs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefs', array($refs));

        return parent::setRefs($refs);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailBody()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailBody', array());

        return parent::getEmailBody();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailBody(\Oro\Bundle\EmailBundle\Entity\EmailBody $emailBody)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailBody', array($emailBody));

        return parent::setEmailBody($emailBody);
    }

    /**
     * {@inheritDoc}
     */
    public function beforeSave()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'beforeSave', array());

        return parent::beforeSave();
    }

    /**
     * {@inheritDoc}
     */
    public function getTo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTo', array());

        return parent::getTo();
    }

    /**
     * {@inheritDoc}
     */
    public function getCc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCc', array());

        return parent::getCc();
    }

    /**
     * {@inheritDoc}
     */
    public function getBcc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBcc', array());

        return parent::getBcc();
    }

    /**
     * {@inheritDoc}
     */
    public function getToCc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToCc', array());

        return parent::getToCc();
    }

    /**
     * {@inheritDoc}
     */
    public function getCcBcc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCcBcc', array());

        return parent::getCcBcc();
    }

    /**
     * {@inheritDoc}
     */
    public function getContacts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContacts', array());

        return parent::getContacts();
    }

    /**
     * {@inheritDoc}
     */
    public function hasAttachments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasAttachments', array());

        return parent::hasAttachments();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailUsers', array());

        return parent::getEmailUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailUserByFolder(\Oro\Bundle\EmailBundle\Entity\EmailFolder $emailFolder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailUserByFolder', array($emailFolder));

        return parent::getEmailUserByFolder($emailFolder);
    }

    /**
     * {@inheritDoc}
     */
    public function addEmailUser(\Oro\Bundle\EmailBundle\Entity\EmailUser $emailUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEmailUser', array($emailUser));

        return parent::addEmailUser($emailUser);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEmailUser(\Oro\Bundle\EmailBundle\Entity\EmailUser $emailUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEmailUser', array($emailUser));

        return parent::removeEmailUser($emailUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getAcceptLanguageHeader()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcceptLanguageHeader', array());

        return parent::getAcceptLanguageHeader();
    }

    /**
     * {@inheritDoc}
     */
    public function setAcceptLanguageHeader($acceptLanguageHeader = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcceptLanguageHeader', array($acceptLanguageHeader));

        return parent::setAcceptLanguageHeader($acceptLanguageHeader);
    }

    /**
     * {@inheritDoc}
     */
    public function getAcceptedLocales()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcceptedLocales', array());

        return parent::getAcceptedLocales();
    }

    /**
     * {@inheritDoc}
     */
    public function supportActivityTarget($targetClass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'supportActivityTarget', array($targetClass));

        return parent::supportActivityTarget($targetClass);
    }

    /**
     * {@inheritDoc}
     */
    public function setUserD41b1c4b($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserD41b1c4b', array($value));

        return parent::setUserD41b1c4b($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setOpportunityC1908b8f($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpportunityC1908b8f', array($value));

        return parent::setOpportunityC1908b8f($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setLeadE5b9c444($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeadE5b9c444', array($value));

        return parent::setLeadE5b9c444($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomer14831de6($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomer14831de6', array($value));

        return parent::setCustomer14831de6($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setContactCdc90e7a($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactCdc90e7a', array($value));

        return parent::setContactCdc90e7a($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setCaseEntity81e7ef35($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaseEntity81e7ef35', array($value));

        return parent::setCaseEntity81e7ef35($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setB2bCustomer22d81e5c($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setB2bCustomer22d81e5c', array($value));

        return parent::setB2bCustomer22d81e5c($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setAccount89f0f6f($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccount89f0f6f', array($value));

        return parent::setAccount89f0f6f($value);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUserD41b1c4b($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUserD41b1c4b', array($value));

        return parent::removeUserD41b1c4b($value);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOpportunityC1908b8f($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOpportunityC1908b8f', array($value));

        return parent::removeOpportunityC1908b8f($value);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLeadE5b9c444($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLeadE5b9c444', array($value));

        return parent::removeLeadE5b9c444($value);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCustomer14831de6($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCustomer14831de6', array($value));

        return parent::removeCustomer14831de6($value);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContactCdc90e7a($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContactCdc90e7a', array($value));

        return parent::removeContactCdc90e7a($value);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCaseEntity81e7ef35($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCaseEntity81e7ef35', array($value));

        return parent::removeCaseEntity81e7ef35($value);
    }

    /**
     * {@inheritDoc}
     */
    public function removeB2bCustomer22d81e5c($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeB2bCustomer22d81e5c', array($value));

        return parent::removeB2bCustomer22d81e5c($value);
    }

    /**
     * {@inheritDoc}
     */
    public function removeActivityTarget($target)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeActivityTarget', array($target));

        return parent::removeActivityTarget($target);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAccount89f0f6f($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAccount89f0f6f', array($value));

        return parent::removeAccount89f0f6f($value);
    }

    /**
     * {@inheritDoc}
     */
    public function hasActivityTarget($target)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasActivityTarget', array($target));

        return parent::hasActivityTarget($target);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserD41b1c4b()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserD41b1c4b', array());

        return parent::getUserD41b1c4b();
    }

    /**
     * {@inheritDoc}
     */
    public function getOpportunityC1908b8f()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpportunityC1908b8f', array());

        return parent::getOpportunityC1908b8f();
    }

    /**
     * {@inheritDoc}
     */
    public function getLeadE5b9c444()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeadE5b9c444', array());

        return parent::getLeadE5b9c444();
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer14831de6()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer14831de6', array());

        return parent::getCustomer14831de6();
    }

    /**
     * {@inheritDoc}
     */
    public function getContactCdc90e7a()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactCdc90e7a', array());

        return parent::getContactCdc90e7a();
    }

    /**
     * {@inheritDoc}
     */
    public function getCaseEntity81e7ef35()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaseEntity81e7ef35', array());

        return parent::getCaseEntity81e7ef35();
    }

    /**
     * {@inheritDoc}
     */
    public function getB2bCustomer22d81e5c()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getB2bCustomer22d81e5c', array());

        return parent::getB2bCustomer22d81e5c();
    }

    /**
     * {@inheritDoc}
     */
    public function getActivityTargets($targetClass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivityTargets', array($targetClass));

        return parent::getActivityTargets($targetClass);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivityTargetEntities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivityTargetEntities', array());

        return parent::getActivityTargetEntities();
    }

    /**
     * {@inheritDoc}
     */
    public function getAccount89f0f6f()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccount89f0f6f', array());

        return parent::getAccount89f0f6f();
    }

    /**
     * {@inheritDoc}
     */
    public function addUserD41b1c4b($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserD41b1c4b', array($value));

        return parent::addUserD41b1c4b($value);
    }

    /**
     * {@inheritDoc}
     */
    public function addOpportunityC1908b8f($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOpportunityC1908b8f', array($value));

        return parent::addOpportunityC1908b8f($value);
    }

    /**
     * {@inheritDoc}
     */
    public function addLeadE5b9c444($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLeadE5b9c444', array($value));

        return parent::addLeadE5b9c444($value);
    }

    /**
     * {@inheritDoc}
     */
    public function addCustomer14831de6($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCustomer14831de6', array($value));

        return parent::addCustomer14831de6($value);
    }

    /**
     * {@inheritDoc}
     */
    public function addContactCdc90e7a($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContactCdc90e7a', array($value));

        return parent::addContactCdc90e7a($value);
    }

    /**
     * {@inheritDoc}
     */
    public function addCaseEntity81e7ef35($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCaseEntity81e7ef35', array($value));

        return parent::addCaseEntity81e7ef35($value);
    }

    /**
     * {@inheritDoc}
     */
    public function addB2bCustomer22d81e5c($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addB2bCustomer22d81e5c', array($value));

        return parent::addB2bCustomer22d81e5c($value);
    }

    /**
     * {@inheritDoc}
     */
    public function addActivityTarget($target)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addActivityTarget', array($target));

        return parent::addActivityTarget($target);
    }

    /**
     * {@inheritDoc}
     */
    public function addAccount89f0f6f($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAccount89f0f6f', array($value));

        return parent::addAccount89f0f6f($value);
    }

}
