<?php

namespace Proxies\__CG__\OroCRM\Bundle\SalesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Opportunity extends \OroCRM\Bundle\SalesBundle\Entity\Opportunity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'status', 'closeReason', 'contact', 'lead', 'owner', 'name', 'closeDate', 'probability', 'budgetAmount', 'closeRevenue', 'customerNeed', 'proposedSolution', 'createdAt', 'updatedAt', 'notes', 'workflowItem', 'workflowStep', 'organization', 'customer', 'ac_last_contact_date_out', 'ac_last_contact_date_in', 'ac_last_contact_date', 'ac_contact_count_out', 'ac_contact_count_in', 'ac_contact_count', 'dataChannel');
        }

        return array('__isInitialized__', 'id', 'status', 'closeReason', 'contact', 'lead', 'owner', 'name', 'closeDate', 'probability', 'budgetAmount', 'closeRevenue', 'customerNeed', 'proposedSolution', 'createdAt', 'updatedAt', 'notes', 'workflowItem', 'workflowStep', 'organization', 'customer', 'ac_last_contact_date_out', 'ac_last_contact_date_in', 'ac_last_contact_date', 'ac_contact_count_out', 'ac_contact_count_in', 'ac_contact_count', 'dataChannel');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Opportunity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setWorkflowItem($workflowItem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkflowItem', array($workflowItem));

        return parent::setWorkflowItem($workflowItem);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkflowItem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkflowItem', array());

        return parent::getWorkflowItem();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorkflowStep($workflowStep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkflowStep', array($workflowStep));

        return parent::setWorkflowStep($workflowStep);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkflowStep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkflowStep', array());

        return parent::getWorkflowStep();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLead($lead)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLead', array($lead));

        return parent::setLead($lead);
    }

    /**
     * {@inheritDoc}
     */
    public function getLead()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLead', array());

        return parent::getLead();
    }

    /**
     * {@inheritDoc}
     */
    public function setBudgetAmount($budgetAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBudgetAmount', array($budgetAmount));

        return parent::setBudgetAmount($budgetAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getBudgetAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBudgetAmount', array());

        return parent::getBudgetAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setCloseDate($closeDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCloseDate', array($closeDate));

        return parent::setCloseDate($closeDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCloseDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCloseDate', array());

        return parent::getCloseDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setContact($contact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContact', array($contact));

        return parent::setContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContact', array());

        return parent::getContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerNeed($customerNeed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerNeed', array($customerNeed));

        return parent::setCustomerNeed($customerNeed);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerNeed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerNeed', array());

        return parent::getCustomerNeed();
    }

    /**
     * {@inheritDoc}
     */
    public function setProbability($probability)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProbability', array($probability));

        return parent::setProbability($probability);
    }

    /**
     * {@inheritDoc}
     */
    public function getProbability()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProbability', array());

        return parent::getProbability();
    }

    /**
     * {@inheritDoc}
     */
    public function setProposedSolution($proposedSolution)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProposedSolution', array($proposedSolution));

        return parent::setProposedSolution($proposedSolution);
    }

    /**
     * {@inheritDoc}
     */
    public function getProposedSolution()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProposedSolution', array());

        return parent::getProposedSolution();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCloseReason($closeReason)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCloseReason', array($closeReason));

        return parent::setCloseReason($closeReason);
    }

    /**
     * {@inheritDoc}
     */
    public function getCloseReason()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCloseReason', array());

        return parent::getCloseReason();
    }

    /**
     * {@inheritDoc}
     */
    public function setCloseRevenue($revenue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCloseRevenue', array($revenue));

        return parent::setCloseRevenue($revenue);
    }

    /**
     * {@inheritDoc}
     */
    public function getCloseRevenue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCloseRevenue', array());

        return parent::getCloseRevenue();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($created));

        return parent::setCreatedAt($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updated));

        return parent::setUpdatedAt($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function beforeSave()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'beforeSave', array());

        return parent::beforeSave();
    }

    /**
     * {@inheritDoc}
     */
    public function beforeUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'beforeUpdate', array());

        return parent::beforeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwner', array());

        return parent::getOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwner($owningUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwner', array($owningUser));

        return parent::setOwner($owningUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotes', array());

        return parent::getNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotes($notes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotes', array($notes));

        return parent::setNotes($notes);
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomer(\OroCRM\Bundle\SalesBundle\Entity\B2bCustomer $customer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomer', array($customer));

        return parent::setCustomer($customer);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer', array());

        return parent::getCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function prePersist(\Doctrine\ORM\Event\LifecycleEventArgs $eventArgs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', array($eventArgs));

        return parent::prePersist($eventArgs);
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganization(\Oro\Bundle\OrganizationBundle\Entity\Organization $organization = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganization', array($organization));

        return parent::setOrganization($organization);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganization()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganization', array());

        return parent::getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    public function removeCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCustomer', array());

        return parent::removeCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setAcLastContactDateOut($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcLastContactDateOut', array($value));

        return parent::setAcLastContactDateOut($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setAcLastContactDateIn($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcLastContactDateIn', array($value));

        return parent::setAcLastContactDateIn($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setAcLastContactDate($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcLastContactDate', array($value));

        return parent::setAcLastContactDate($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setAcContactCountOut($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcContactCountOut', array($value));

        return parent::setAcContactCountOut($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setAcContactCountIn($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcContactCountIn', array($value));

        return parent::setAcContactCountIn($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setAcContactCount($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcContactCount', array($value));

        return parent::setAcContactCount($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getAcLastContactDateOut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcLastContactDateOut', array());

        return parent::getAcLastContactDateOut();
    }

    /**
     * {@inheritDoc}
     */
    public function getAcLastContactDateIn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcLastContactDateIn', array());

        return parent::getAcLastContactDateIn();
    }

    /**
     * {@inheritDoc}
     */
    public function getAcLastContactDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcLastContactDate', array());

        return parent::getAcLastContactDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getAcContactCountOut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcContactCountOut', array());

        return parent::getAcContactCountOut();
    }

    /**
     * {@inheritDoc}
     */
    public function getAcContactCountIn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcContactCountIn', array());

        return parent::getAcContactCountIn();
    }

    /**
     * {@inheritDoc}
     */
    public function getAcContactCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcContactCount', array());

        return parent::getAcContactCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataChannel(\OroCRM\Bundle\ChannelBundle\Entity\Channel $channel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataChannel', array($channel));

        return parent::setDataChannel($channel);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataChannel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataChannel', array());

        return parent::getDataChannel();
    }

}
