<?php

namespace Proxies\__CG__\OroCRM\Bundle\ContactBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Contact extends \OroCRM\Bundle\ContactBundle\Entity\Contact implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'namePrefix', 'firstName', 'middleName', 'lastName', 'nameSuffix', 'gender', 'birthday', 'description', 'source', 'method', 'owner', 'assignedTo', 'reportsTo', 'jobTitle', 'email', 'emails', 'phones', 'fax', 'skype', 'twitter', 'facebook', 'googlePlus', 'linkedIn', 'tags', 'addresses', 'groups', 'accounts', 'createdBy', 'updatedBy', 'createdAt', 'updatedAt', 'organization', 'picture', 'ac_last_contact_date_out', 'ac_last_contact_date_in', 'ac_last_contact_date', 'ac_contact_count_out', 'ac_contact_count_in', 'ac_contact_count');
        }

        return array('__isInitialized__', 'id', 'namePrefix', 'firstName', 'middleName', 'lastName', 'nameSuffix', 'gender', 'birthday', 'description', 'source', 'method', 'owner', 'assignedTo', 'reportsTo', 'jobTitle', 'email', 'emails', 'phones', 'fax', 'skype', 'twitter', 'facebook', 'googlePlus', 'linkedIn', 'tags', 'addresses', 'groups', 'accounts', 'createdBy', 'updatedBy', 'createdAt', 'updatedAt', 'organization', 'picture', 'ac_last_contact_date_out', 'ac_last_contact_date_in', 'ac_last_contact_date', 'ac_contact_count_out', 'ac_contact_count_in', 'ac_contact_count');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Contact $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClass', array());

        return parent::getClass();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailFields()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailFields', array());

        return parent::getEmailFields();
    }

    /**
     * {@inheritDoc}
     */
    public function setAssignedTo($assignedTo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssignedTo', array($assignedTo));

        return parent::setAssignedTo($assignedTo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssignedTo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssignedTo', array());

        return parent::getAssignedTo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setSource($source)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSource', array($source));

        return parent::setSource($source);
    }

    /**
     * {@inheritDoc}
     */
    public function getSource()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSource', array());

        return parent::getSource();
    }

    /**
     * {@inheritDoc}
     */
    public function setMethod($method)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMethod', array($method));

        return parent::setMethod($method);
    }

    /**
     * {@inheritDoc}
     */
    public function getMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMethod', array());

        return parent::getMethod();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwner($owningUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwner', array($owningUser));

        return parent::setOwner($owningUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwner', array());

        return parent::getOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function setReportsTo($reportsTo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReportsTo', array($reportsTo));

        return parent::setReportsTo($reportsTo);
    }

    /**
     * {@inheritDoc}
     */
    public function getReportsTo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReportsTo', array());

        return parent::getReportsTo();
    }

    /**
     * {@inheritDoc}
     */
    public function setJobTitle($jobTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJobTitle', array($jobTitle));

        return parent::setJobTitle($jobTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getJobTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobTitle', array());

        return parent::getJobTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', array($fax));

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', array());

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setSkype($skype)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSkype', array($skype));

        return parent::setSkype($skype);
    }

    /**
     * {@inheritDoc}
     */
    public function getSkype()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSkype', array());

        return parent::getSkype();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebook($facebookUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebook', array($facebookUrl));

        return parent::setFacebook($facebookUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebook()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebook', array());

        return parent::getFacebook();
    }

    /**
     * {@inheritDoc}
     */
    public function setGooglePlus($googlePlusUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGooglePlus', array($googlePlusUrl));

        return parent::setGooglePlus($googlePlusUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getGooglePlus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGooglePlus', array());

        return parent::getGooglePlus();
    }

    /**
     * {@inheritDoc}
     */
    public function setLinkedIn($linkedInUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinkedIn', array($linkedInUrl));

        return parent::setLinkedIn($linkedInUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getLinkedIn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinkedIn', array());

        return parent::getLinkedIn();
    }

    /**
     * {@inheritDoc}
     */
    public function setTwitter($twitterUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwitter', array($twitterUrl));

        return parent::setTwitter($twitterUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getTwitter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwitter', array());

        return parent::getTwitter();
    }

    /**
     * {@inheritDoc}
     */
    public function getTaggableId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaggableId', array());

        return parent::getTaggableId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTags()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTags', array());

        return parent::getTags();
    }

    /**
     * {@inheritDoc}
     */
    public function setTags($tags)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTags', array($tags));

        return parent::setTags($tags);
    }

    /**
     * {@inheritDoc}
     */
    public function resetEmails($emails)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'resetEmails', array($emails));

        return parent::resetEmails($emails);
    }

    /**
     * {@inheritDoc}
     */
    public function addEmail(\OroCRM\Bundle\ContactBundle\Entity\ContactEmail $email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEmail', array($email));

        return parent::addEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEmail(\OroCRM\Bundle\ContactBundle\Entity\ContactEmail $email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEmail', array($email));

        return parent::removeEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmails', array());

        return parent::getEmails();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function hasEmail(\OroCRM\Bundle\ContactBundle\Entity\ContactEmail $email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasEmail', array($email));

        return parent::hasEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimaryEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimaryEmail', array());

        return parent::getPrimaryEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimaryEmail(\OroCRM\Bundle\ContactBundle\Entity\ContactEmail $email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimaryEmail', array($email));

        return parent::setPrimaryEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function resetPhones($phones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'resetPhones', array($phones));

        return parent::resetPhones($phones);
    }

    /**
     * {@inheritDoc}
     */
    public function addPhone(\OroCRM\Bundle\ContactBundle\Entity\ContactPhone $phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPhone', array($phone));

        return parent::addPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function removePhone(\OroCRM\Bundle\ContactBundle\Entity\ContactPhone $phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePhone', array($phone));

        return parent::removePhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhones', array());

        return parent::getPhones();
    }

    /**
     * {@inheritDoc}
     */
    public function hasPhone(\OroCRM\Bundle\ContactBundle\Entity\ContactPhone $phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasPhone', array($phone));

        return parent::hasPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimaryPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimaryPhone', array());

        return parent::getPrimaryPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimaryPhone(\OroCRM\Bundle\ContactBundle\Entity\ContactPhone $phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimaryPhone', array($phone));

        return parent::setPrimaryPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function addAddress(\Oro\Bundle\AddressBundle\Entity\AbstractAddress $address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAddress', array($address));

        return parent::addAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimaryAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimaryAddress', array());

        return parent::getPrimaryAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimaryAddress(\OroCRM\Bundle\ContactBundle\Entity\ContactAddress $address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimaryAddress', array($address));

        return parent::setPrimaryAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressType(\OroCRM\Bundle\ContactBundle\Entity\ContactAddress $address, \Oro\Bundle\AddressBundle\Entity\AddressType $addressType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressType', array($address, $addressType));

        return parent::setAddressType($address, $addressType);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressByType(\Oro\Bundle\AddressBundle\Entity\AddressType $type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressByType', array($type));

        return parent::getAddressByType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressByTypeName($typeName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressByTypeName', array($typeName));

        return parent::getAddressByTypeName($typeName);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupLabelsAsString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupLabelsAsString', array());

        return parent::getGroupLabelsAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupLabels()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupLabels', array());

        return parent::getGroupLabels();
    }

    /**
     * {@inheritDoc}
     */
    public function getGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroups', array());

        return parent::getGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function addGroup(\OroCRM\Bundle\ContactBundle\Entity\Group $group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGroup', array($group));

        return parent::addGroup($group);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGroup(\OroCRM\Bundle\ContactBundle\Entity\Group $group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGroup', array($group));

        return parent::removeGroup($group);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccounts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccounts', array());

        return parent::getAccounts();
    }

    /**
     * {@inheritDoc}
     */
    public function addAccount(\OroCRM\Bundle\AccountBundle\Entity\Account $account)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAccount', array($account));

        return parent::addAccount($account);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAccount(\OroCRM\Bundle\AccountBundle\Entity\Account $account)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAccount', array($account));

        return parent::removeAccount($account);
    }

    /**
     * {@inheritDoc}
     */
    public function hasAccounts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasAccounts', array());

        return parent::hasAccounts();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($createdBy));

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy($updatedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', array($updatedBy));

        return parent::setUpdatedBy($updatedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', array());

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganization(\Oro\Bundle\OrganizationBundle\Entity\Organization $organization = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganization', array($organization));

        return parent::setOrganization($organization);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganization()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganization', array());

        return parent::getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    public function setPicture($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPicture', array($value));

        return parent::setPicture($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setAcLastContactDateOut($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcLastContactDateOut', array($value));

        return parent::setAcLastContactDateOut($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setAcLastContactDateIn($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcLastContactDateIn', array($value));

        return parent::setAcLastContactDateIn($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setAcLastContactDate($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcLastContactDate', array($value));

        return parent::setAcLastContactDate($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setAcContactCountOut($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcContactCountOut', array($value));

        return parent::setAcContactCountOut($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setAcContactCountIn($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcContactCountIn', array($value));

        return parent::setAcContactCountIn($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setAcContactCount($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcContactCount', array($value));

        return parent::setAcContactCount($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getPicture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPicture', array());

        return parent::getPicture();
    }

    /**
     * {@inheritDoc}
     */
    public function getAcLastContactDateOut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcLastContactDateOut', array());

        return parent::getAcLastContactDateOut();
    }

    /**
     * {@inheritDoc}
     */
    public function getAcLastContactDateIn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcLastContactDateIn', array());

        return parent::getAcLastContactDateIn();
    }

    /**
     * {@inheritDoc}
     */
    public function getAcLastContactDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcLastContactDate', array());

        return parent::getAcLastContactDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getAcContactCountOut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcContactCountOut', array());

        return parent::getAcContactCountOut();
    }

    /**
     * {@inheritDoc}
     */
    public function getAcContactCountIn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcContactCountIn', array());

        return parent::getAcContactCountIn();
    }

    /**
     * {@inheritDoc}
     */
    public function getAcContactCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcContactCount', array());

        return parent::getAcContactCount();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setNamePrefix($prefix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNamePrefix', array($prefix));

        return parent::setNamePrefix($prefix);
    }

    /**
     * {@inheritDoc}
     */
    public function getNamePrefix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNamePrefix', array());

        return parent::getNamePrefix();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', array($firstName));

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', array());

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setMiddleName($middleName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMiddleName', array($middleName));

        return parent::setMiddleName($middleName);
    }

    /**
     * {@inheritDoc}
     */
    public function getMiddleName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMiddleName', array());

        return parent::getMiddleName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($lastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', array($lastName));

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', array());

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameSuffix($nameSuffix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameSuffix', array($nameSuffix));

        return parent::setNameSuffix($nameSuffix);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameSuffix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameSuffix', array());

        return parent::getNameSuffix();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender($gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', array($gender));

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', array());

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthday($birthday)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthday', array($birthday));

        return parent::setBirthday($birthday);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthday()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthday', array());

        return parent::getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function resetAddresses($addresses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'resetAddresses', array($addresses));

        return parent::resetAddresses($addresses);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAddress(\Oro\Bundle\AddressBundle\Entity\AbstractAddress $address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAddress', array($address));

        return parent::removeAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddresses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddresses', array());

        return parent::getAddresses();
    }

    /**
     * {@inheritDoc}
     */
    public function hasAddress(\Oro\Bundle\AddressBundle\Entity\AbstractAddress $address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasAddress', array($address));

        return parent::hasAddress($address);
    }

}
