<?php

namespace Proxies\__CG__\OroCRM\Bundle\MagentoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cart extends \OroCRM\Bundle\MagentoBundle\Entity\Cart implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'cartItems', 'customer', 'store', 'itemsQty', 'itemsCount', 'baseCurrencyCode', 'storeCurrencyCode', 'quoteCurrencyCode', 'storeToBaseRate', 'storeToQuoteRate', 'email', 'giftMessage', 'isGuest', 'shippingAddress', 'billingAddress', 'paymentDetails', 'status', 'opportunity', 'relatedCalls', 'relatedEmails', 'notes', 'workflowItem', 'workflowStep', 'statusMessage', 'owner', 'organization', 'id', 'subTotal', 'grandTotal', 'taxAmount', 'createdAt', 'updatedAt', 'channel', 'originId', 'firstName', 'lastName', 'dataChannel');
        }

        return array('__isInitialized__', 'cartItems', 'customer', 'store', 'itemsQty', 'itemsCount', 'baseCurrencyCode', 'storeCurrencyCode', 'quoteCurrencyCode', 'storeToBaseRate', 'storeToQuoteRate', 'email', 'giftMessage', 'isGuest', 'shippingAddress', 'billingAddress', 'paymentDetails', 'status', 'opportunity', 'relatedCalls', 'relatedEmails', 'notes', 'workflowItem', 'workflowStep', 'statusMessage', 'owner', 'organization', 'id', 'subTotal', 'grandTotal', 'taxAmount', 'createdAt', 'updatedAt', 'channel', 'originId', 'firstName', 'lastName', 'dataChannel');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cart $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setWorkflowItem($workflowItem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkflowItem', array($workflowItem));

        return parent::setWorkflowItem($workflowItem);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkflowItem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkflowItem', array());

        return parent::getWorkflowItem();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorkflowStep($workflowStep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkflowStep', array($workflowStep));

        return parent::setWorkflowStep($workflowStep);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkflowStep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkflowStep', array());

        return parent::getWorkflowStep();
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedCalls()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedCalls', array());

        return parent::getRelatedCalls();
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedCall(\OroCRM\Bundle\CallBundle\Entity\Call $call)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedCall', array($call));

        return parent::addRelatedCall($call);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedCall(\OroCRM\Bundle\CallBundle\Entity\Call $call)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedCall', array($call));

        return parent::removeRelatedCall($call);
    }

    /**
     * {@inheritDoc}
     */
    public function hasRelatedCall(\OroCRM\Bundle\CallBundle\Entity\Call $call)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasRelatedCall', array($call));

        return parent::hasRelatedCall($call);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedEmails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedEmails', array());

        return parent::getRelatedEmails();
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedEmail(\Oro\Bundle\EmailBundle\Entity\Email $email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedEmail', array($email));

        return parent::addRelatedEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedEmail(\Oro\Bundle\EmailBundle\Entity\Email $email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedEmail', array($email));

        return parent::removeRelatedEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function hasRelatedEmail(\Oro\Bundle\EmailBundle\Entity\Email $email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasRelatedEmail', array($email));

        return parent::hasRelatedEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getCartItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCartItems', array());

        return parent::getCartItems();
    }

    /**
     * {@inheritDoc}
     */
    public function setCartItems(\Doctrine\Common\Collections\Collection $cartItems)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCartItems', array($cartItems));

        return parent::setCartItems($cartItems);
    }

    /**
     * {@inheritDoc}
     */
    public function setStore($store)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStore', array($store));

        return parent::setStore($store);
    }

    /**
     * {@inheritDoc}
     */
    public function getStore()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStore', array());

        return parent::getStore();
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer', array());

        return parent::getCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomer(\OroCRM\Bundle\MagentoBundle\Entity\Customer $customer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomer', array($customer));

        return parent::setCustomer($customer);
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingAddress(\OroCRM\Bundle\MagentoBundle\Entity\CartAddress $shippingAddress = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingAddress', array($shippingAddress));

        return parent::setShippingAddress($shippingAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingAddress(\OroCRM\Bundle\MagentoBundle\Entity\CartAddress $billingAddress = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingAddress', array($billingAddress));

        return parent::setBillingAddress($billingAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingAddress', array());

        return parent::getBillingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingAddress', array());

        return parent::getShippingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemsQty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemsQty', array());

        return parent::getItemsQty();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemsQty($itemsQty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemsQty', array($itemsQty));

        return parent::setItemsQty($itemsQty);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubTotal', array());

        return parent::getSubTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getQuoteCurrencyCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuoteCurrencyCode', array());

        return parent::getQuoteCurrencyCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuoteCurrencyCode($quoteCurrencyCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuoteCurrencyCode', array($quoteCurrencyCode));

        return parent::setQuoteCurrencyCode($quoteCurrencyCode);
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentDetails($paymentDetails)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentDetails', array($paymentDetails));

        return parent::setPaymentDetails($paymentDetails);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentDetails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentDetails', array());

        return parent::getPaymentDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setBaseCurrencyCode($baseCurrencyCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBaseCurrencyCode', array($baseCurrencyCode));

        return parent::setBaseCurrencyCode($baseCurrencyCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getBaseCurrencyCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaseCurrencyCode', array());

        return parent::getBaseCurrencyCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setGiftMessage($giftMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGiftMessage', array($giftMessage));

        return parent::setGiftMessage($giftMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getGiftMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGiftMessage', array());

        return parent::getGiftMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsGuest($isGuest)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsGuest', array($isGuest));

        return parent::setIsGuest($isGuest);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsGuest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsGuest', array());

        return parent::getIsGuest();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemsCount($itemsCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemsCount', array($itemsCount));

        return parent::setItemsCount($itemsCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemsCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemsCount', array());

        return parent::getItemsCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setStoreCurrencyCode($storeCurrencyCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStoreCurrencyCode', array($storeCurrencyCode));

        return parent::setStoreCurrencyCode($storeCurrencyCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getStoreCurrencyCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStoreCurrencyCode', array());

        return parent::getStoreCurrencyCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setStoreToBaseRate($storeToBaseRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStoreToBaseRate', array($storeToBaseRate));

        return parent::setStoreToBaseRate($storeToBaseRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getStoreToBaseRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStoreToBaseRate', array());

        return parent::getStoreToBaseRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setStoreToQuoteRate($storeToQuoteRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStoreToQuoteRate', array($storeToQuoteRate));

        return parent::setStoreToQuoteRate($storeToQuoteRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getStoreToQuoteRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStoreToQuoteRate', array());

        return parent::getStoreToQuoteRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpportunity($opportunity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpportunity', array($opportunity));

        return parent::setOpportunity($opportunity);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpportunity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpportunity', array());

        return parent::getOpportunity();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotes($notes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotes', array($notes));

        return parent::setNotes($notes);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotes', array());

        return parent::getNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function beforeSave()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'beforeSave', array());

        return parent::beforeSave();
    }

    /**
     * {@inheritDoc}
     */
    public function doPreUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'doPreUpdate', array());

        return parent::doPreUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatusMessage($statusMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatusMessage', array($statusMessage));

        return parent::setStatusMessage($statusMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusMessage', array());

        return parent::getStatusMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function getOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwner', array());

        return parent::getOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwner(\Oro\Bundle\UserBundle\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwner', array($user));

        return parent::setOwner($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganization(\Oro\Bundle\OrganizationBundle\Entity\Organization $organization = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganization', array($organization));

        return parent::setOrganization($organization);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganization()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganization', array());

        return parent::getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrandTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrandTotal', array());

        return parent::getGrandTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrandTotal($grandTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrandTotal', array($grandTotal));

        return parent::setGrandTotal($grandTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubTotal($subTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubTotal', array($subTotal));

        return parent::setSubTotal($subTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxAmount($taxAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxAmount', array($taxAmount));

        return parent::setTaxAmount($taxAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxAmount', array());

        return parent::getTaxAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataChannel(\OroCRM\Bundle\ChannelBundle\Entity\Channel $channel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataChannel', array($channel));

        return parent::setDataChannel($channel);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataChannel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataChannel', array());

        return parent::getDataChannel();
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', array());

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', array());

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginId($originId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginId', array($originId));

        return parent::setOriginId($originId);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginId', array());

        return parent::getOriginId();
    }

    /**
     * {@inheritDoc}
     */
    public function setChannel(\Oro\Bundle\IntegrationBundle\Entity\Channel $integration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChannel', array($integration));

        return parent::setChannel($integration);
    }

    /**
     * {@inheritDoc}
     */
    public function getChannel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChannel', array());

        return parent::getChannel();
    }

    /**
     * {@inheritDoc}
     */
    public function getChannelName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChannelName', array());

        return parent::getChannelName();
    }

}
